import {Project} from "../types/project";

const projects: Project[] = [
    {
        "name": "Mimont",
        "slug": "mimont",
        "thumbnailUri": "project_content/mimont/thumb.png",
        "splash": "project_content/mimont/splash.jpg",
        "content": "",
        "shortDescription": "Interactive experience exploring the act of kissing.",
        "year": 2020,
        "tags": ["unity", "networking", "experience", "emotional", "csharp", "hku"],
        "techs": ["Unity 2019.3", "UDP networking", "C#"],
        "isFavorite": true,
    },
    {
        "name": "Procedural tree generator",
        "slug": "tree-generator",
        "thumbnailUri": "project_content/tree-gen/thumb.png",
        "splash": "project_content/tree-gen/thumb.png",
        "content": "",
        "shortDescription": "Low-poly tree mesh generator in Unity.",
        "year": 2020,
        "tags": ["unity", "3d modeling", "procedural", "c-sharp", "hku"],
        "techs": ["Unity 2019", "C#"]
    },
    {
        "name": "Where is Fluffy?",
        "slug": "fluffy",
        "thumbnailUri": "project_content/fluffy/thumb.jpg",
        "splash": "project_content/fluffy/thumb.jpg",
        "content": "",
        "shortDescription": "Interactive story about a young child overcoming their fear.",
        "year": 2021,
        "tags": ["unity", "dialogue", "entertainment", "storytelling", "c-sharp", "hku"],
        "techs": ["Unity 2021.1", "Yarn Spinner", "C#"],
        "isFavorite": true,
    },
    {
        "name": "Connect for Coffee",
        "slug": "connect-for-coffee",
        "thumbnailUri": "project_content/connect-for-coffee/thumb.png",
        "splash": "project_content/connect-for-coffee/logo_notext.svg",
        "content": "",
        "shortDescription": "Meet strangers while searching for WiFi.",
        "year": 2019,
        "tags": ["interaction", "web", "nodejs", "emotional", "humanity", "social", "hku"],
        "techs": ["Node.js", "Websockets", "Raspberry Pi", "WiFi"],
        "isFavorite": true,
    },
    {
        "name": "Game of Life",
        "slug": "game-of-life",
        "thumbnailUri": "project_content/gol/thumb.png",
        "splash": "project_content/gol/splash.png",
        "content": "",
        "shortDescription": "Windows console version of the game of life in C++.",
        "year": 2019,
        "tags": ["c++", "hku"],
        "techs": ["C++"]
    },
    {
        "name": "Digital Treasure Chest",
        "slug": "treasure-chest",
        "thumbnailUri": "project_content/treasure-chest/thumb.jpg",
        "splash": "project_content/treasure-chest/splash.jpg",
        "content": "",
        "shortDescription": "Custom-built chest that opens with a unique, digital code.",
        "year": 2018,
        "tags": ["arduino", "c++", "hardware", "hku"],
        "techs": ["Arduino", "C/C++", "Electronics", "Wood & metalworking"],
        "isFavorite": true,
    },
    {
        "name": "Mapsnap",
        "slug": "mapsnap",
        "thumbnailUri": "project_content/mapsnap/thumb.gif",
        "splash": "project_content/mapsnap/thumb.gif",
        "content": "",
        "shortDescription": "A command line tool to create snapshots and timelapses of OpenStreetMap.",
        "year": 2021,
        "tags": ["c-sharp", "openstreetmap", "osm", "dotnet", "image-processing", "cli"],
        "techs": ["C#", ".NET 6.0", "OpenStreetMap", "CLI"],
        "isFavorite": true,
    },
    // {
    //     "name": "The Journalist",
    //     "slug": "the-journalist",
    //     "thumbnailUri": "project_content/journalist/thumb.png",
    //     "splash": "project_content/journalist/thumb.png",
    //     "content": "",
    //     "shortDescription": "Custom-built chest that opens with a unique, digital code.",
    //     "year": "2020-2021",
    //     "tags": ["web", "typescript", "node-js", "database", "full-stack"],
    //     "techs": ["Webapp", "Vue", "Node.js", "MongoDB"]
    // },
    {
        "name": "Shaders in MonoGame",
        "slug": "graphprog",
        "thumbnailUri": "project_content/graphprog/thumb.jpg",
        "splash": "project_content/graphprog/splash.jpg",
        "content": "",
        "shortDescription": "OpenGL shader programming.",
        "year": 2021,
        "tags": ["arduino", "c++", "hardware", "hku"],
        "techs": ["C#", "MonoGame", "OpenGL", "HLSL"]
    },
    {
        "name": "Building Analyzer",
        "slug": "buildings-osm",
        "thumbnailUri": "project_content/buildings-osm/splash.png",
        "splash": "project_content/buildings-osm/splash.png",
        "content": "",
        "shortDescription": "Node.js tool to help track progress mapping a town on OpenStreetMap",
        "year": 2020,
        "tags": ["nodejs", "javascript", "openstreetmap", "cli"],
        "techs": ["Node.js", "OverPass API", "OpenStreetMap"],
    },
    {
        "name": "Cliffside cave",
        "slug": "cliffside-cave",
        "thumbnailUri": "project_content/envmod/thumb.jpg",
        "splash": "project_content/envmod/splash.jpg",
        "content": "",
        "shortDescription": "A small cave, hidden away and forgotten...",
        "year": 2020,
        "tags": ["3d modeling", "environment", "storytelling", "hku"],
        "techs": ["Substance Painter", "Blender", "Unity HDRP"]
    },
    // {
    //     // TODO
    //     "name": "Simfluencer",
    //     "slug": "simfluencer",
    //     "thumbnailUri": "project_content/simfluencer/thumb.png",
    //     "splash": "project_content/treasure-chest/splash.jpg",
    //     "content": simfluencer,
    //     "shortDescription": "Game about the impact of spreading fake news.",
    //     "year": "2020",
    //     "tags": ["unity", "c#", "hku"],
    //     "techs": ["Unity", "C#"]
    // },
    {
        "name": "Basic Networking",
        "slug": "basic-networking",
        "thumbnailUri": "project_content/basic-networking/thumb.png",
        "splash": "project_content/basic-networking/thumb.png",
        "content": "",
        "shortDescription": "Server-client UDP networking with the Unity Transport API.",
        "year": 2021,
        "tags": ["unity", "csharp", "networking"],
        "techs": ["Unity", "C#", "UDP Networking"]
    },
    // {
    //     "name": "Test Project",
    //     "slug": "test-project",
    //     "thumbnailUri": "project_content/thumbX.png",
    //     "splash": "project_content/thumbX.png",
    //     "content": example,
    //     "shortDescription": "",
    //     "year": 2081,
    //     "tags": ["unity", "dialogue", "entertainment", "storytelling"],
    //     "techs": ["Unity 2021.1", "Yarn Spinner", "C#"]
    // },
];

export default projects;